spring.datasource.url=${DOCTOR_DB_URL:jdbc:postgresql://localhost:5432/doctordb}
spring.datasource.username=${DOCTOR_DB_USERNAME:doctordb}
spring.datasource.password=${DOCTOR_DB_PASSWORD:doctordb}

security.jwt.enforce=false
